// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/user_progress_card.proto

package user_progress_card

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortTermMemory int32

const (
	ShortTermMemory_STM_UNKNOWN ShortTermMemory = 0
	ShortTermMemory_STM_BAD     ShortTermMemory = 1
	ShortTermMemory_STM_NORMAL  ShortTermMemory = 2
	ShortTermMemory_STM_GOOD    ShortTermMemory = 3
	ShortTermMemory_STM_PERFECT ShortTermMemory = 4
)

// Enum value maps for ShortTermMemory.
var (
	ShortTermMemory_name = map[int32]string{
		0: "STM_UNKNOWN",
		1: "STM_BAD",
		2: "STM_NORMAL",
		3: "STM_GOOD",
		4: "STM_PERFECT",
	}
	ShortTermMemory_value = map[string]int32{
		"STM_UNKNOWN": 0,
		"STM_BAD":     1,
		"STM_NORMAL":  2,
		"STM_GOOD":    3,
		"STM_PERFECT": 4,
	}
)

func (x ShortTermMemory) Enum() *ShortTermMemory {
	p := new(ShortTermMemory)
	*p = x
	return p
}

func (x ShortTermMemory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShortTermMemory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_progress_card_proto_enumTypes[0].Descriptor()
}

func (ShortTermMemory) Type() protoreflect.EnumType {
	return &file_proto_user_progress_card_proto_enumTypes[0]
}

func (x ShortTermMemory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShortTermMemory.Descriptor instead.
func (ShortTermMemory) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_progress_card_proto_rawDescGZIP(), []int{0}
}

type RecallQuality int32

const (
	RecallQuality_BAD     RecallQuality = 0
	RecallQuality_NORMAL  RecallQuality = 1
	RecallQuality_GOOD    RecallQuality = 2
	RecallQuality_PERFECT RecallQuality = 3
)

// Enum value maps for RecallQuality.
var (
	RecallQuality_name = map[int32]string{
		0: "BAD",
		1: "NORMAL",
		2: "GOOD",
		3: "PERFECT",
	}
	RecallQuality_value = map[string]int32{
		"BAD":     0,
		"NORMAL":  1,
		"GOOD":    2,
		"PERFECT": 3,
	}
)

func (x RecallQuality) Enum() *RecallQuality {
	p := new(RecallQuality)
	*p = x
	return p
}

func (x RecallQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecallQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_progress_card_proto_enumTypes[1].Descriptor()
}

func (RecallQuality) Type() protoreflect.EnumType {
	return &file_proto_user_progress_card_proto_enumTypes[1]
}

func (x RecallQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecallQuality.Descriptor instead.
func (RecallQuality) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_progress_card_proto_rawDescGZIP(), []int{1}
}

type UserProgressCard struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardId          int32                  `protobuf:"varint,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Question        string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Answer          string                 `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	NextReviewDate  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=next_review_date,json=nextReviewDate,proto3,oneof" json:"next_review_date,omitempty"`
	LastReviewedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_reviewed_at,json=lastReviewedAt,proto3,oneof" json:"last_reviewed_at,omitempty"`
	ShortTermMemory ShortTermMemory        `protobuf:"varint,7,opt,name=short_term_memory,json=shortTermMemory,proto3,enum=user_progress_card.ShortTermMemory" json:"short_term_memory,omitempty"`
	LongTermMemory  int32                  `protobuf:"varint,8,opt,name=long_term_memory,json=longTermMemory,proto3" json:"long_term_memory,omitempty"`
	RepetitionCount int32                  `protobuf:"varint,9,opt,name=repetition_count,json=repetitionCount,proto3" json:"repetition_count,omitempty"`
	DeckId          int32                  `protobuf:"varint,10,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserProgressCard) Reset() {
	*x = UserProgressCard{}
	mi := &file_proto_user_progress_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgressCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgressCard) ProtoMessage() {}

func (x *UserProgressCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgressCard.ProtoReflect.Descriptor instead.
func (*UserProgressCard) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_card_proto_rawDescGZIP(), []int{0}
}

func (x *UserProgressCard) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProgressCard) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *UserProgressCard) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *UserProgressCard) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *UserProgressCard) GetNextReviewDate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextReviewDate
	}
	return nil
}

func (x *UserProgressCard) GetLastReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReviewedAt
	}
	return nil
}

func (x *UserProgressCard) GetShortTermMemory() ShortTermMemory {
	if x != nil {
		return x.ShortTermMemory
	}
	return ShortTermMemory_STM_UNKNOWN
}

func (x *UserProgressCard) GetLongTermMemory() int32 {
	if x != nil {
		return x.LongTermMemory
	}
	return 0
}

func (x *UserProgressCard) GetRepetitionCount() int32 {
	if x != nil {
		return x.RepetitionCount
	}
	return 0
}

func (x *UserProgressCard) GetDeckId() int32 {
	if x != nil {
		return x.DeckId
	}
	return 0
}

type GetProgressCardsByDeckIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckID        int32                  `protobuf:"varint,1,opt,name=deckID,proto3" json:"deckID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressCardsByDeckIDRequest) Reset() {
	*x = GetProgressCardsByDeckIDRequest{}
	mi := &file_proto_user_progress_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressCardsByDeckIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressCardsByDeckIDRequest) ProtoMessage() {}

func (x *GetProgressCardsByDeckIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressCardsByDeckIDRequest.ProtoReflect.Descriptor instead.
func (*GetProgressCardsByDeckIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_card_proto_rawDescGZIP(), []int{1}
}

func (x *GetProgressCardsByDeckIDRequest) GetDeckID() int32 {
	if x != nil {
		return x.DeckID
	}
	return 0
}

type GetProgressCardsByDeckIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgressCards []*UserProgressCard    `protobuf:"bytes,1,rep,name=progress_cards,json=progressCards,proto3" json:"progress_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressCardsByDeckIDResponse) Reset() {
	*x = GetProgressCardsByDeckIDResponse{}
	mi := &file_proto_user_progress_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressCardsByDeckIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressCardsByDeckIDResponse) ProtoMessage() {}

func (x *GetProgressCardsByDeckIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressCardsByDeckIDResponse.ProtoReflect.Descriptor instead.
func (*GetProgressCardsByDeckIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_card_proto_rawDescGZIP(), []int{2}
}

func (x *GetProgressCardsByDeckIDResponse) GetProgressCards() []*UserProgressCard {
	if x != nil {
		return x.ProgressCards
	}
	return nil
}

type CardReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quality       RecallQuality          `protobuf:"varint,2,opt,name=quality,proto3,enum=user_progress_card.RecallQuality" json:"quality,omitempty"`
	Cards         []*UserProgressCard    `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardReviewRequest) Reset() {
	*x = CardReviewRequest{}
	mi := &file_proto_user_progress_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardReviewRequest) ProtoMessage() {}

func (x *CardReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardReviewRequest.ProtoReflect.Descriptor instead.
func (*CardReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_card_proto_rawDescGZIP(), []int{3}
}

func (x *CardReviewRequest) GetQuality() RecallQuality {
	if x != nil {
		return x.Quality
	}
	return RecallQuality_BAD
}

func (x *CardReviewRequest) GetCards() []*UserProgressCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

type CardReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*UserProgressCard    `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardReviewResponse) Reset() {
	*x = CardReviewResponse{}
	mi := &file_proto_user_progress_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardReviewResponse) ProtoMessage() {}

func (x *CardReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardReviewResponse.ProtoReflect.Descriptor instead.
func (*CardReviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_card_proto_rawDescGZIP(), []int{4}
}

func (x *CardReviewResponse) GetCards() []*UserProgressCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ProgressCards struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*UserProgressCard    `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressCards) Reset() {
	*x = ProgressCards{}
	mi := &file_proto_user_progress_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressCards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressCards) ProtoMessage() {}

func (x *ProgressCards) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressCards.ProtoReflect.Descriptor instead.
func (*ProgressCards) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_card_proto_rawDescGZIP(), []int{5}
}

func (x *ProgressCards) GetCards() []*UserProgressCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

type GetCardsForTodayReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        int32                  `protobuf:"varint,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsForTodayReviewRequest) Reset() {
	*x = GetCardsForTodayReviewRequest{}
	mi := &file_proto_user_progress_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsForTodayReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsForTodayReviewRequest) ProtoMessage() {}

func (x *GetCardsForTodayReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_progress_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsForTodayReviewRequest.ProtoReflect.Descriptor instead.
func (*GetCardsForTodayReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_progress_card_proto_rawDescGZIP(), []int{6}
}

func (x *GetCardsForTodayReviewRequest) GetDeckId() int32 {
	if x != nil {
		return x.DeckId
	}
	return 0
}

var File_proto_user_progress_card_proto protoreflect.FileDescriptor

const file_proto_user_progress_card_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/user_progress_card.proto\x12\x12user_progress_card\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x03\n" +
	"\x10UserProgressCard\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\x05R\x06cardId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x04 \x01(\tR\x06answer\x12I\n" +
	"\x10next_review_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0enextReviewDate\x88\x01\x01\x12I\n" +
	"\x10last_reviewed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x0elastReviewedAt\x88\x01\x01\x12O\n" +
	"\x11short_term_memory\x18\a \x01(\x0e2#.user_progress_card.ShortTermMemoryR\x0fshortTermMemory\x12(\n" +
	"\x10long_term_memory\x18\b \x01(\x05R\x0elongTermMemory\x12)\n" +
	"\x10repetition_count\x18\t \x01(\x05R\x0frepetitionCount\x12\x17\n" +
	"\adeck_id\x18\n" +
	" \x01(\x05R\x06deckIdB\x13\n" +
	"\x11_next_review_dateB\x13\n" +
	"\x11_last_reviewed_at\"9\n" +
	"\x1fGetProgressCardsByDeckIDRequest\x12\x16\n" +
	"\x06deckID\x18\x01 \x01(\x05R\x06deckID\"o\n" +
	" GetProgressCardsByDeckIDResponse\x12K\n" +
	"\x0eprogress_cards\x18\x01 \x03(\v2$.user_progress_card.UserProgressCardR\rprogressCards\"\x8c\x01\n" +
	"\x11CardReviewRequest\x12;\n" +
	"\aquality\x18\x02 \x01(\x0e2!.user_progress_card.RecallQualityR\aquality\x12:\n" +
	"\x05cards\x18\x01 \x03(\v2$.user_progress_card.UserProgressCardR\x05cards\"P\n" +
	"\x12CardReviewResponse\x12:\n" +
	"\x05cards\x18\x01 \x03(\v2$.user_progress_card.UserProgressCardR\x05cards\"K\n" +
	"\rProgressCards\x12:\n" +
	"\x05cards\x18\x01 \x03(\v2$.user_progress_card.UserProgressCardR\x05cards\"8\n" +
	"\x1dGetCardsForTodayReviewRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\x05R\x06deckId*^\n" +
	"\x0fShortTermMemory\x12\x0f\n" +
	"\vSTM_UNKNOWN\x10\x00\x12\v\n" +
	"\aSTM_BAD\x10\x01\x12\x0e\n" +
	"\n" +
	"STM_NORMAL\x10\x02\x12\f\n" +
	"\bSTM_GOOD\x10\x03\x12\x0f\n" +
	"\vSTM_PERFECT\x10\x04*;\n" +
	"\rRecallQuality\x12\a\n" +
	"\x03BAD\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\b\n" +
	"\x04GOOD\x10\x02\x12\v\n" +
	"\aPERFECT\x10\x032\xc1\x04\n" +
	"\x17UserProgressCardService\x12\x85\x01\n" +
	"\x18GetProgressCardsByDeckID\x123.user_progress_card.GetProgressCardsByDeckIDRequest\x1a4.user_progress_card.GetProgressCardsByDeckIDResponse\x12i\n" +
	"\x18SubmitProgressCardReview\x12%.user_progress_card.CardReviewRequest\x1a&.user_progress_card.CardReviewResponse\x12^\n" +
	"\x16SelectNewProgressCards\x12!.user_progress_card.ProgressCards\x1a!.user_progress_card.ProgressCards\x12c\n" +
	"\x1bSelectFamiliarProgressCards\x12!.user_progress_card.ProgressCards\x1a!.user_progress_card.ProgressCards\x12n\n" +
	"\x16GetCardsForTodayReview\x121.user_progress_card.GetCardsForTodayReviewRequest\x1a!.user_progress_card.ProgressCardsB@Z>infrastructure/grpc_infr/user_progress_card;user_progress_cardb\x06proto3"

var (
	file_proto_user_progress_card_proto_rawDescOnce sync.Once
	file_proto_user_progress_card_proto_rawDescData []byte
)

func file_proto_user_progress_card_proto_rawDescGZIP() []byte {
	file_proto_user_progress_card_proto_rawDescOnce.Do(func() {
		file_proto_user_progress_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_progress_card_proto_rawDesc), len(file_proto_user_progress_card_proto_rawDesc)))
	})
	return file_proto_user_progress_card_proto_rawDescData
}

var file_proto_user_progress_card_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_user_progress_card_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_user_progress_card_proto_goTypes = []any{
	(ShortTermMemory)(0),                     // 0: user_progress_card.ShortTermMemory
	(RecallQuality)(0),                       // 1: user_progress_card.RecallQuality
	(*UserProgressCard)(nil),                 // 2: user_progress_card.UserProgressCard
	(*GetProgressCardsByDeckIDRequest)(nil),  // 3: user_progress_card.GetProgressCardsByDeckIDRequest
	(*GetProgressCardsByDeckIDResponse)(nil), // 4: user_progress_card.GetProgressCardsByDeckIDResponse
	(*CardReviewRequest)(nil),                // 5: user_progress_card.CardReviewRequest
	(*CardReviewResponse)(nil),               // 6: user_progress_card.CardReviewResponse
	(*ProgressCards)(nil),                    // 7: user_progress_card.ProgressCards
	(*GetCardsForTodayReviewRequest)(nil),    // 8: user_progress_card.GetCardsForTodayReviewRequest
	(*timestamppb.Timestamp)(nil),            // 9: google.protobuf.Timestamp
}
var file_proto_user_progress_card_proto_depIdxs = []int32{
	9,  // 0: user_progress_card.UserProgressCard.next_review_date:type_name -> google.protobuf.Timestamp
	9,  // 1: user_progress_card.UserProgressCard.last_reviewed_at:type_name -> google.protobuf.Timestamp
	0,  // 2: user_progress_card.UserProgressCard.short_term_memory:type_name -> user_progress_card.ShortTermMemory
	2,  // 3: user_progress_card.GetProgressCardsByDeckIDResponse.progress_cards:type_name -> user_progress_card.UserProgressCard
	1,  // 4: user_progress_card.CardReviewRequest.quality:type_name -> user_progress_card.RecallQuality
	2,  // 5: user_progress_card.CardReviewRequest.cards:type_name -> user_progress_card.UserProgressCard
	2,  // 6: user_progress_card.CardReviewResponse.cards:type_name -> user_progress_card.UserProgressCard
	2,  // 7: user_progress_card.ProgressCards.cards:type_name -> user_progress_card.UserProgressCard
	3,  // 8: user_progress_card.UserProgressCardService.GetProgressCardsByDeckID:input_type -> user_progress_card.GetProgressCardsByDeckIDRequest
	5,  // 9: user_progress_card.UserProgressCardService.SubmitProgressCardReview:input_type -> user_progress_card.CardReviewRequest
	7,  // 10: user_progress_card.UserProgressCardService.SelectNewProgressCards:input_type -> user_progress_card.ProgressCards
	7,  // 11: user_progress_card.UserProgressCardService.SelectFamiliarProgressCards:input_type -> user_progress_card.ProgressCards
	8,  // 12: user_progress_card.UserProgressCardService.GetCardsForTodayReview:input_type -> user_progress_card.GetCardsForTodayReviewRequest
	4,  // 13: user_progress_card.UserProgressCardService.GetProgressCardsByDeckID:output_type -> user_progress_card.GetProgressCardsByDeckIDResponse
	6,  // 14: user_progress_card.UserProgressCardService.SubmitProgressCardReview:output_type -> user_progress_card.CardReviewResponse
	7,  // 15: user_progress_card.UserProgressCardService.SelectNewProgressCards:output_type -> user_progress_card.ProgressCards
	7,  // 16: user_progress_card.UserProgressCardService.SelectFamiliarProgressCards:output_type -> user_progress_card.ProgressCards
	7,  // 17: user_progress_card.UserProgressCardService.GetCardsForTodayReview:output_type -> user_progress_card.ProgressCards
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_user_progress_card_proto_init() }
func file_proto_user_progress_card_proto_init() {
	if File_proto_user_progress_card_proto != nil {
		return
	}
	file_proto_user_progress_card_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_progress_card_proto_rawDesc), len(file_proto_user_progress_card_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_progress_card_proto_goTypes,
		DependencyIndexes: file_proto_user_progress_card_proto_depIdxs,
		EnumInfos:         file_proto_user_progress_card_proto_enumTypes,
		MessageInfos:      file_proto_user_progress_card_proto_msgTypes,
	}.Build()
	File_proto_user_progress_card_proto = out.File
	file_proto_user_progress_card_proto_goTypes = nil
	file_proto_user_progress_card_proto_depIdxs = nil
}
