// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/global_card.proto

package global_card

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeckID        int32                  `protobuf:"varint,2,opt,name=deckID,proto3" json:"deckID,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	AuthorID      int32                  `protobuf:"varint,5,opt,name=authorID,proto3" json:"authorID,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalCard) Reset() {
	*x = GlobalCard{}
	mi := &file_proto_global_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalCard) ProtoMessage() {}

func (x *GlobalCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalCard.ProtoReflect.Descriptor instead.
func (*GlobalCard) Descriptor() ([]byte, []int) {
	return file_proto_global_card_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalCard) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GlobalCard) GetDeckID() int32 {
	if x != nil {
		return x.DeckID
	}
	return 0
}

func (x *GlobalCard) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GlobalCard) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *GlobalCard) GetAuthorID() int32 {
	if x != nil {
		return x.AuthorID
	}
	return 0
}

func (x *GlobalCard) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GlobalCard) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GlobalCard) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CreateGlobalCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	DeckID        int32                  `protobuf:"varint,3,opt,name=deckID,proto3" json:"deckID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGlobalCardRequest) Reset() {
	*x = CreateGlobalCardRequest{}
	mi := &file_proto_global_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGlobalCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGlobalCardRequest) ProtoMessage() {}

func (x *CreateGlobalCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGlobalCardRequest.ProtoReflect.Descriptor instead.
func (*CreateGlobalCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_card_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGlobalCardRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *CreateGlobalCardRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *CreateGlobalCardRequest) GetDeckID() int32 {
	if x != nil {
		return x.DeckID
	}
	return 0
}

type CreateGlobalCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGlobalCardResponse) Reset() {
	*x = CreateGlobalCardResponse{}
	mi := &file_proto_global_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGlobalCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGlobalCardResponse) ProtoMessage() {}

func (x *CreateGlobalCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGlobalCardResponse.ProtoReflect.Descriptor instead.
func (*CreateGlobalCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_card_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGlobalCardResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGlobalCardsByDeckIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckID        int32                  `protobuf:"varint,1,opt,name=deckID,proto3" json:"deckID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalCardsByDeckIDRequest) Reset() {
	*x = GetGlobalCardsByDeckIDRequest{}
	mi := &file_proto_global_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalCardsByDeckIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalCardsByDeckIDRequest) ProtoMessage() {}

func (x *GetGlobalCardsByDeckIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalCardsByDeckIDRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalCardsByDeckIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_card_proto_rawDescGZIP(), []int{3}
}

func (x *GetGlobalCardsByDeckIDRequest) GetDeckID() int32 {
	if x != nil {
		return x.DeckID
	}
	return 0
}

type GetGlobalCardsByDeckIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalCards   []*GlobalCard          `protobuf:"bytes,1,rep,name=globalCards,proto3" json:"globalCards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalCardsByDeckIDResponse) Reset() {
	*x = GetGlobalCardsByDeckIDResponse{}
	mi := &file_proto_global_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalCardsByDeckIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalCardsByDeckIDResponse) ProtoMessage() {}

func (x *GetGlobalCardsByDeckIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalCardsByDeckIDResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalCardsByDeckIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_card_proto_rawDescGZIP(), []int{4}
}

func (x *GetGlobalCardsByDeckIDResponse) GetGlobalCards() []*GlobalCard {
	if x != nil {
		return x.GlobalCards
	}
	return nil
}

type UpdateGlobalCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	CardID        int32                  `protobuf:"varint,3,opt,name=cardID,proto3" json:"cardID,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGlobalCardRequest) Reset() {
	*x = UpdateGlobalCardRequest{}
	mi := &file_proto_global_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGlobalCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalCardRequest) ProtoMessage() {}

func (x *UpdateGlobalCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateGlobalCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_card_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGlobalCardRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *UpdateGlobalCardRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *UpdateGlobalCardRequest) GetCardID() int32 {
	if x != nil {
		return x.CardID
	}
	return 0
}

func (x *UpdateGlobalCardRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateGlobalCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	ConflictCard  *GlobalCard            `protobuf:"bytes,2,opt,name=conflictCard,proto3" json:"conflictCard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGlobalCardResponse) Reset() {
	*x = UpdateGlobalCardResponse{}
	mi := &file_proto_global_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGlobalCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalCardResponse) ProtoMessage() {}

func (x *UpdateGlobalCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalCardResponse.ProtoReflect.Descriptor instead.
func (*UpdateGlobalCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_card_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGlobalCardResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *UpdateGlobalCardResponse) GetConflictCard() *GlobalCard {
	if x != nil {
		return x.ConflictCard
	}
	return nil
}

type DeleteGlobalCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int32                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGlobalCardRequest) Reset() {
	*x = DeleteGlobalCardRequest{}
	mi := &file_proto_global_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGlobalCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGlobalCardRequest) ProtoMessage() {}

func (x *DeleteGlobalCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGlobalCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteGlobalCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_card_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGlobalCardRequest) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

type DeleteGlobalCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGlobalCardResponse) Reset() {
	*x = DeleteGlobalCardResponse{}
	mi := &file_proto_global_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGlobalCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGlobalCardResponse) ProtoMessage() {}

func (x *DeleteGlobalCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGlobalCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteGlobalCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_card_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteGlobalCardResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

var File_proto_global_card_proto protoreflect.FileDescriptor

const file_proto_global_card_proto_rawDesc = "" +
	"\n" +
	"\x17proto/global_card.proto\x12\vglobal_card\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x02\n" +
	"\n" +
	"GlobalCard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06deckID\x18\x02 \x01(\x05R\x06deckID\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x04 \x01(\tR\x06answer\x12\x1a\n" +
	"\bauthorID\x18\x05 \x01(\x05R\bauthorID\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\"e\n" +
	"\x17CreateGlobalCardRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x16\n" +
	"\x06deckID\x18\x03 \x01(\x05R\x06deckID\"*\n" +
	"\x18CreateGlobalCardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"7\n" +
	"\x1dGetGlobalCardsByDeckIDRequest\x12\x16\n" +
	"\x06deckID\x18\x01 \x01(\x05R\x06deckID\"[\n" +
	"\x1eGetGlobalCardsByDeckIDResponse\x129\n" +
	"\vglobalCards\x18\x01 \x03(\v2\x17.global_card.GlobalCardR\vglobalCards\"\x7f\n" +
	"\x17UpdateGlobalCardRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x16\n" +
	"\x06cardID\x18\x03 \x01(\x05R\x06cardID\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"u\n" +
	"\x18UpdateGlobalCardResponse\x12\x1c\n" +
	"\tisSuccess\x18\x01 \x01(\bR\tisSuccess\x12;\n" +
	"\fconflictCard\x18\x02 \x01(\v2\x17.global_card.GlobalCardR\fconflictCard\"2\n" +
	"\x17DeleteGlobalCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x05R\x06cardId\"8\n" +
	"\x18DeleteGlobalCardResponse\x12\x1c\n" +
	"\tisSuccess\x18\x01 \x01(\bR\tisSuccess2\xa9\x03\n" +
	"\x11GlobalCardService\x12_\n" +
	"\x10CreateGlobalCard\x12$.global_card.CreateGlobalCardRequest\x1a%.global_card.CreateGlobalCardResponse\x12q\n" +
	"\x16GetGlobalCardsByDeckID\x12*.global_card.GetGlobalCardsByDeckIDRequest\x1a+.global_card.GetGlobalCardsByDeckIDResponse\x12_\n" +
	"\x10UpdateGlobalCard\x12$.global_card.UpdateGlobalCardRequest\x1a%.global_card.UpdateGlobalCardResponse\x12_\n" +
	"\x10DeleteGlobalCard\x12$.global_card.DeleteGlobalCardRequest\x1a%.global_card.DeleteGlobalCardResponseB2Z0infrastructure/grpc_infr/global_card;global_cardb\x06proto3"

var (
	file_proto_global_card_proto_rawDescOnce sync.Once
	file_proto_global_card_proto_rawDescData []byte
)

func file_proto_global_card_proto_rawDescGZIP() []byte {
	file_proto_global_card_proto_rawDescOnce.Do(func() {
		file_proto_global_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_global_card_proto_rawDesc), len(file_proto_global_card_proto_rawDesc)))
	})
	return file_proto_global_card_proto_rawDescData
}

var file_proto_global_card_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_global_card_proto_goTypes = []any{
	(*GlobalCard)(nil),                     // 0: global_card.GlobalCard
	(*CreateGlobalCardRequest)(nil),        // 1: global_card.CreateGlobalCardRequest
	(*CreateGlobalCardResponse)(nil),       // 2: global_card.CreateGlobalCardResponse
	(*GetGlobalCardsByDeckIDRequest)(nil),  // 3: global_card.GetGlobalCardsByDeckIDRequest
	(*GetGlobalCardsByDeckIDResponse)(nil), // 4: global_card.GetGlobalCardsByDeckIDResponse
	(*UpdateGlobalCardRequest)(nil),        // 5: global_card.UpdateGlobalCardRequest
	(*UpdateGlobalCardResponse)(nil),       // 6: global_card.UpdateGlobalCardResponse
	(*DeleteGlobalCardRequest)(nil),        // 7: global_card.DeleteGlobalCardRequest
	(*DeleteGlobalCardResponse)(nil),       // 8: global_card.DeleteGlobalCardResponse
	(*timestamppb.Timestamp)(nil),          // 9: google.protobuf.Timestamp
}
var file_proto_global_card_proto_depIdxs = []int32{
	9, // 0: global_card.GlobalCard.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: global_card.GlobalCard.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: global_card.GetGlobalCardsByDeckIDResponse.globalCards:type_name -> global_card.GlobalCard
	0, // 3: global_card.UpdateGlobalCardResponse.conflictCard:type_name -> global_card.GlobalCard
	1, // 4: global_card.GlobalCardService.CreateGlobalCard:input_type -> global_card.CreateGlobalCardRequest
	3, // 5: global_card.GlobalCardService.GetGlobalCardsByDeckID:input_type -> global_card.GetGlobalCardsByDeckIDRequest
	5, // 6: global_card.GlobalCardService.UpdateGlobalCard:input_type -> global_card.UpdateGlobalCardRequest
	7, // 7: global_card.GlobalCardService.DeleteGlobalCard:input_type -> global_card.DeleteGlobalCardRequest
	2, // 8: global_card.GlobalCardService.CreateGlobalCard:output_type -> global_card.CreateGlobalCardResponse
	4, // 9: global_card.GlobalCardService.GetGlobalCardsByDeckID:output_type -> global_card.GetGlobalCardsByDeckIDResponse
	6, // 10: global_card.GlobalCardService.UpdateGlobalCard:output_type -> global_card.UpdateGlobalCardResponse
	8, // 11: global_card.GlobalCardService.DeleteGlobalCard:output_type -> global_card.DeleteGlobalCardResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_global_card_proto_init() }
func file_proto_global_card_proto_init() {
	if File_proto_global_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_global_card_proto_rawDesc), len(file_proto_global_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_global_card_proto_goTypes,
		DependencyIndexes: file_proto_global_card_proto_depIdxs,
		MessageInfos:      file_proto_global_card_proto_msgTypes,
	}.Build()
	File_proto_global_card_proto = out.File
	file_proto_global_card_proto_goTypes = nil
	file_proto_global_card_proto_depIdxs = nil
}
