// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/global_deck.proto

package global_deck

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalDeck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	AuthorID      int32                  `protobuf:"varint,4,opt,name=authorID,proto3" json:"authorID,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsPublic      bool                   `protobuf:"varint,7,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Version       int32                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalDeck) Reset() {
	*x = GlobalDeck{}
	mi := &file_proto_global_deck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalDeck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalDeck) ProtoMessage() {}

func (x *GlobalDeck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalDeck.ProtoReflect.Descriptor instead.
func (*GlobalDeck) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalDeck) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GlobalDeck) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GlobalDeck) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *GlobalDeck) GetAuthorID() int32 {
	if x != nil {
		return x.AuthorID
	}
	return 0
}

func (x *GlobalDeck) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GlobalDeck) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GlobalDeck) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *GlobalDeck) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GlobalDeck) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CreateGlobalDeckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,3,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGlobalDeckRequest) Reset() {
	*x = CreateGlobalDeckRequest{}
	mi := &file_proto_global_deck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGlobalDeckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGlobalDeckRequest) ProtoMessage() {}

func (x *CreateGlobalDeckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGlobalDeckRequest.ProtoReflect.Descriptor instead.
func (*CreateGlobalDeckRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGlobalDeckRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateGlobalDeckRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGlobalDeckRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type CreateGlobalDeckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGlobalDeckResponse) Reset() {
	*x = CreateGlobalDeckResponse{}
	mi := &file_proto_global_deck_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGlobalDeckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGlobalDeckResponse) ProtoMessage() {}

func (x *CreateGlobalDeckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGlobalDeckResponse.ProtoReflect.Descriptor instead.
func (*CreateGlobalDeckResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGlobalDeckResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEditableDecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEditableDecksRequest) Reset() {
	*x = GetEditableDecksRequest{}
	mi := &file_proto_global_deck_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEditableDecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEditableDecksRequest) ProtoMessage() {}

func (x *GetEditableDecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEditableDecksRequest.ProtoReflect.Descriptor instead.
func (*GetEditableDecksRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{3}
}

type GetEditableDecksResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ListOfGlobalDecks []*GlobalDeck          `protobuf:"bytes,1,rep,name=listOfGlobalDecks,proto3" json:"listOfGlobalDecks,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetEditableDecksResponse) Reset() {
	*x = GetEditableDecksResponse{}
	mi := &file_proto_global_deck_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEditableDecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEditableDecksResponse) ProtoMessage() {}

func (x *GetEditableDecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEditableDecksResponse.ProtoReflect.Descriptor instead.
func (*GetEditableDecksResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{4}
}

func (x *GetEditableDecksResponse) GetListOfGlobalDecks() []*GlobalDeck {
	if x != nil {
		return x.ListOfGlobalDecks
	}
	return nil
}

type UpdateGlobalDeckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalDeck    *GlobalDeck            `protobuf:"bytes,1,opt,name=globalDeck,proto3" json:"globalDeck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGlobalDeckRequest) Reset() {
	*x = UpdateGlobalDeckRequest{}
	mi := &file_proto_global_deck_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGlobalDeckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalDeckRequest) ProtoMessage() {}

func (x *UpdateGlobalDeckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalDeckRequest.ProtoReflect.Descriptor instead.
func (*UpdateGlobalDeckRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGlobalDeckRequest) GetGlobalDeck() *GlobalDeck {
	if x != nil {
		return x.GlobalDeck
	}
	return nil
}

type UpdateGlobalDeckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConflictDeck  *GlobalDeck            `protobuf:"bytes,1,opt,name=conflictDeck,proto3" json:"conflictDeck,omitempty"`
	IsSuccess     bool                   `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGlobalDeckResponse) Reset() {
	*x = UpdateGlobalDeckResponse{}
	mi := &file_proto_global_deck_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGlobalDeckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalDeckResponse) ProtoMessage() {}

func (x *UpdateGlobalDeckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalDeckResponse.ProtoReflect.Descriptor instead.
func (*UpdateGlobalDeckResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGlobalDeckResponse) GetConflictDeck() *GlobalDeck {
	if x != nil {
		return x.ConflictDeck
	}
	return nil
}

func (x *UpdateGlobalDeckResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type GetGlobalDeckInfoByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalDeckInfoByIDRequest) Reset() {
	*x = GetGlobalDeckInfoByIDRequest{}
	mi := &file_proto_global_deck_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalDeckInfoByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalDeckInfoByIDRequest) ProtoMessage() {}

func (x *GetGlobalDeckInfoByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalDeckInfoByIDRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalDeckInfoByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{7}
}

func (x *GetGlobalDeckInfoByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGlobalDeckInfoByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalDeck    *GlobalDeck            `protobuf:"bytes,1,opt,name=globalDeck,proto3" json:"globalDeck,omitempty"`
	AuthName      string                 `protobuf:"bytes,2,opt,name=authName,proto3" json:"authName,omitempty"`
	EditorNames   []string               `protobuf:"bytes,3,rep,name=editorNames,proto3" json:"editorNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalDeckInfoByIDResponse) Reset() {
	*x = GetGlobalDeckInfoByIDResponse{}
	mi := &file_proto_global_deck_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalDeckInfoByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalDeckInfoByIDResponse) ProtoMessage() {}

func (x *GetGlobalDeckInfoByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalDeckInfoByIDResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalDeckInfoByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{8}
}

func (x *GetGlobalDeckInfoByIDResponse) GetGlobalDeck() *GlobalDeck {
	if x != nil {
		return x.GlobalDeck
	}
	return nil
}

func (x *GetGlobalDeckInfoByIDResponse) GetAuthName() string {
	if x != nil {
		return x.AuthName
	}
	return ""
}

func (x *GetGlobalDeckInfoByIDResponse) GetEditorNames() []string {
	if x != nil {
		return x.EditorNames
	}
	return nil
}

type DeleteGlobalDeckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckID        int32                  `protobuf:"varint,1,opt,name=deckID,proto3" json:"deckID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGlobalDeckRequest) Reset() {
	*x = DeleteGlobalDeckRequest{}
	mi := &file_proto_global_deck_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGlobalDeckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGlobalDeckRequest) ProtoMessage() {}

func (x *DeleteGlobalDeckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGlobalDeckRequest.ProtoReflect.Descriptor instead.
func (*DeleteGlobalDeckRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteGlobalDeckRequest) GetDeckID() int32 {
	if x != nil {
		return x.DeckID
	}
	return 0
}

type DeleteGlobalDeckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGlobalDeckResponse) Reset() {
	*x = DeleteGlobalDeckResponse{}
	mi := &file_proto_global_deck_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGlobalDeckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGlobalDeckResponse) ProtoMessage() {}

func (x *DeleteGlobalDeckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGlobalDeckResponse.ProtoReflect.Descriptor instead.
func (*DeleteGlobalDeckResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteGlobalDeckResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type SearchGlobalDecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGlobalDecksRequest) Reset() {
	*x = SearchGlobalDecksRequest{}
	mi := &file_proto_global_deck_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGlobalDecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGlobalDecksRequest) ProtoMessage() {}

func (x *SearchGlobalDecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGlobalDecksRequest.ProtoReflect.Descriptor instead.
func (*SearchGlobalDecksRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{11}
}

func (x *SearchGlobalDecksRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchGlobalDecksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchGlobalDecksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchGlobalDecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResultDeck    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGlobalDecksResponse) Reset() {
	*x = SearchGlobalDecksResponse{}
	mi := &file_proto_global_deck_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGlobalDecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGlobalDecksResponse) ProtoMessage() {}

func (x *SearchGlobalDecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGlobalDecksResponse.ProtoReflect.Descriptor instead.
func (*SearchGlobalDecksResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{12}
}

func (x *SearchGlobalDecksResponse) GetResults() []*SearchResultDeck {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchGlobalDecksResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type SearchResultDeck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Deck           *GlobalDeck            `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	IsAlreadyAdded bool                   `protobuf:"varint,2,opt,name=is_already_added,json=isAlreadyAdded,proto3" json:"is_already_added,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchResultDeck) Reset() {
	*x = SearchResultDeck{}
	mi := &file_proto_global_deck_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultDeck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultDeck) ProtoMessage() {}

func (x *SearchResultDeck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultDeck.ProtoReflect.Descriptor instead.
func (*SearchResultDeck) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResultDeck) GetDeck() *GlobalDeck {
	if x != nil {
		return x.Deck
	}
	return nil
}

func (x *SearchResultDeck) GetIsAlreadyAdded() bool {
	if x != nil {
		return x.IsAlreadyAdded
	}
	return false
}

type AddDeckToLearningDecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckID        int32                  `protobuf:"varint,1,opt,name=deckID,proto3" json:"deckID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDeckToLearningDecksRequest) Reset() {
	*x = AddDeckToLearningDecksRequest{}
	mi := &file_proto_global_deck_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeckToLearningDecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeckToLearningDecksRequest) ProtoMessage() {}

func (x *AddDeckToLearningDecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeckToLearningDecksRequest.ProtoReflect.Descriptor instead.
func (*AddDeckToLearningDecksRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{14}
}

func (x *AddDeckToLearningDecksRequest) GetDeckID() int32 {
	if x != nil {
		return x.DeckID
	}
	return 0
}

type AddDeckToLearningDecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDeckToLearningDecksResponse) Reset() {
	*x = AddDeckToLearningDecksResponse{}
	mi := &file_proto_global_deck_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeckToLearningDecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeckToLearningDecksResponse) ProtoMessage() {}

func (x *AddDeckToLearningDecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeckToLearningDecksResponse.ProtoReflect.Descriptor instead.
func (*AddDeckToLearningDecksResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{15}
}

func (x *AddDeckToLearningDecksResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type AddEditorToGlobalDeckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deck_ID       int32                  `protobuf:"varint,1,opt,name=deck_ID,json=deckID,proto3" json:"deck_ID,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEditorToGlobalDeckRequest) Reset() {
	*x = AddEditorToGlobalDeckRequest{}
	mi := &file_proto_global_deck_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEditorToGlobalDeckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEditorToGlobalDeckRequest) ProtoMessage() {}

func (x *AddEditorToGlobalDeckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEditorToGlobalDeckRequest.ProtoReflect.Descriptor instead.
func (*AddEditorToGlobalDeckRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{16}
}

func (x *AddEditorToGlobalDeckRequest) GetDeck_ID() int32 {
	if x != nil {
		return x.Deck_ID
	}
	return 0
}

func (x *AddEditorToGlobalDeckRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type AddEditorToGlobalDeckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEditorToGlobalDeckResponse) Reset() {
	*x = AddEditorToGlobalDeckResponse{}
	mi := &file_proto_global_deck_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEditorToGlobalDeckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEditorToGlobalDeckResponse) ProtoMessage() {}

func (x *AddEditorToGlobalDeckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEditorToGlobalDeckResponse.ProtoReflect.Descriptor instead.
func (*AddEditorToGlobalDeckResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{17}
}

func (x *AddEditorToGlobalDeckResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type DemoteEditorToLearnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deck_ID       int32                  `protobuf:"varint,1,opt,name=deck_ID,json=deckID,proto3" json:"deck_ID,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoteEditorToLearnerRequest) Reset() {
	*x = DemoteEditorToLearnerRequest{}
	mi := &file_proto_global_deck_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoteEditorToLearnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoteEditorToLearnerRequest) ProtoMessage() {}

func (x *DemoteEditorToLearnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoteEditorToLearnerRequest.ProtoReflect.Descriptor instead.
func (*DemoteEditorToLearnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{18}
}

func (x *DemoteEditorToLearnerRequest) GetDeck_ID() int32 {
	if x != nil {
		return x.Deck_ID
	}
	return 0
}

func (x *DemoteEditorToLearnerRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type DemoteEditorToLearnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoteEditorToLearnerResponse) Reset() {
	*x = DemoteEditorToLearnerResponse{}
	mi := &file_proto_global_deck_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoteEditorToLearnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoteEditorToLearnerResponse) ProtoMessage() {}

func (x *DemoteEditorToLearnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_global_deck_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoteEditorToLearnerResponse.ProtoReflect.Descriptor instead.
func (*DemoteEditorToLearnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_global_deck_proto_rawDescGZIP(), []int{19}
}

func (x *DemoteEditorToLearnerResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

var File_proto_global_deck_proto protoreflect.FileDescriptor

const file_proto_global_deck_proto_rawDesc = "" +
	"\n" +
	"\x17proto/global_deck.proto\x12\vglobal_deck\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x02\n" +
	"\n" +
	"GlobalDeck\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\bauthorID\x18\x04 \x01(\x05R\bauthorID\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1a\n" +
	"\bisPublic\x18\a \x01(\bR\bisPublic\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x18\n" +
	"\aversion\x18\t \x01(\x05R\aversionB\x0e\n" +
	"\f_description\"m\n" +
	"\x17CreateGlobalDeckRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bisPublic\x18\x03 \x01(\bR\bisPublic\"*\n" +
	"\x18CreateGlobalDeckResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x19\n" +
	"\x17GetEditableDecksRequest\"a\n" +
	"\x18GetEditableDecksResponse\x12E\n" +
	"\x11listOfGlobalDecks\x18\x01 \x03(\v2\x17.global_deck.GlobalDeckR\x11listOfGlobalDecks\"R\n" +
	"\x17UpdateGlobalDeckRequest\x127\n" +
	"\n" +
	"globalDeck\x18\x01 \x01(\v2\x17.global_deck.GlobalDeckR\n" +
	"globalDeck\"u\n" +
	"\x18UpdateGlobalDeckResponse\x12;\n" +
	"\fconflictDeck\x18\x01 \x01(\v2\x17.global_deck.GlobalDeckR\fconflictDeck\x12\x1c\n" +
	"\tisSuccess\x18\x02 \x01(\bR\tisSuccess\".\n" +
	"\x1cGetGlobalDeckInfoByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x96\x01\n" +
	"\x1dGetGlobalDeckInfoByIDResponse\x127\n" +
	"\n" +
	"globalDeck\x18\x01 \x01(\v2\x17.global_deck.GlobalDeckR\n" +
	"globalDeck\x12\x1a\n" +
	"\bauthName\x18\x02 \x01(\tR\bauthName\x12 \n" +
	"\veditorNames\x18\x03 \x03(\tR\veditorNames\"1\n" +
	"\x17DeleteGlobalDeckRequest\x12\x16\n" +
	"\x06deckID\x18\x01 \x01(\x05R\x06deckID\"8\n" +
	"\x18DeleteGlobalDeckResponse\x12\x1c\n" +
	"\tisSuccess\x18\x01 \x01(\bR\tisSuccess\"^\n" +
	"\x18SearchGlobalDecksRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"o\n" +
	"\x19SearchGlobalDecksResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.global_deck.SearchResultDeckR\aresults\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"i\n" +
	"\x10SearchResultDeck\x12+\n" +
	"\x04deck\x18\x01 \x01(\v2\x17.global_deck.GlobalDeckR\x04deck\x12(\n" +
	"\x10is_already_added\x18\x02 \x01(\bR\x0eisAlreadyAdded\"7\n" +
	"\x1dAddDeckToLearningDecksRequest\x12\x16\n" +
	"\x06deckID\x18\x01 \x01(\x05R\x06deckID\">\n" +
	"\x1eAddDeckToLearningDecksResponse\x12\x1c\n" +
	"\tisSuccess\x18\x01 \x01(\bR\tisSuccess\"T\n" +
	"\x1cAddEditorToGlobalDeckRequest\x12\x17\n" +
	"\adeck_ID\x18\x01 \x01(\x05R\x06deckID\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"=\n" +
	"\x1dAddEditorToGlobalDeckResponse\x12\x1c\n" +
	"\tisSuccess\x18\x01 \x01(\bR\tisSuccess\"T\n" +
	"\x1cDemoteEditorToLearnerRequest\x12\x17\n" +
	"\adeck_ID\x18\x01 \x01(\x05R\x06deckID\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"=\n" +
	"\x1dDemoteEditorToLearnerResponse\x12\x1c\n" +
	"\tisSuccess\x18\x01 \x01(\bR\tisSuccess2\xc4\a\n" +
	"\x11GlobalDeckService\x12_\n" +
	"\x10CreateGlobalDeck\x12$.global_deck.CreateGlobalDeckRequest\x1a%.global_deck.CreateGlobalDeckResponse\x12e\n" +
	"\x16GetEditableGlobalDecks\x12$.global_deck.GetEditableDecksRequest\x1a%.global_deck.GetEditableDecksResponse\x12_\n" +
	"\x10UpdateGlobalDeck\x12$.global_deck.UpdateGlobalDeckRequest\x1a%.global_deck.UpdateGlobalDeckResponse\x12n\n" +
	"\x15GetGlobalDeckInfoByID\x12).global_deck.GetGlobalDeckInfoByIDRequest\x1a*.global_deck.GetGlobalDeckInfoByIDResponse\x12_\n" +
	"\x10DeleteGlobalDeck\x12$.global_deck.DeleteGlobalDeckRequest\x1a%.global_deck.DeleteGlobalDeckResponse\x12b\n" +
	"\x11SearchGlobalDecks\x12%.global_deck.SearchGlobalDecksRequest\x1a&.global_deck.SearchGlobalDecksResponse\x12q\n" +
	"\x16AddDeckToLearningDecks\x12*.global_deck.AddDeckToLearningDecksRequest\x1a+.global_deck.AddDeckToLearningDecksResponse\x12n\n" +
	"\x15AddEditorToGlobalDeck\x12).global_deck.AddEditorToGlobalDeckRequest\x1a*.global_deck.AddEditorToGlobalDeckResponse\x12n\n" +
	"\x15DemoteEditorToLearner\x12).global_deck.DemoteEditorToLearnerRequest\x1a*.global_deck.DemoteEditorToLearnerResponseB2Z0infrastructure/grpc_infr/global_deck;global_deckb\x06proto3"

var (
	file_proto_global_deck_proto_rawDescOnce sync.Once
	file_proto_global_deck_proto_rawDescData []byte
)

func file_proto_global_deck_proto_rawDescGZIP() []byte {
	file_proto_global_deck_proto_rawDescOnce.Do(func() {
		file_proto_global_deck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_global_deck_proto_rawDesc), len(file_proto_global_deck_proto_rawDesc)))
	})
	return file_proto_global_deck_proto_rawDescData
}

var file_proto_global_deck_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_global_deck_proto_goTypes = []any{
	(*GlobalDeck)(nil),                     // 0: global_deck.GlobalDeck
	(*CreateGlobalDeckRequest)(nil),        // 1: global_deck.CreateGlobalDeckRequest
	(*CreateGlobalDeckResponse)(nil),       // 2: global_deck.CreateGlobalDeckResponse
	(*GetEditableDecksRequest)(nil),        // 3: global_deck.GetEditableDecksRequest
	(*GetEditableDecksResponse)(nil),       // 4: global_deck.GetEditableDecksResponse
	(*UpdateGlobalDeckRequest)(nil),        // 5: global_deck.UpdateGlobalDeckRequest
	(*UpdateGlobalDeckResponse)(nil),       // 6: global_deck.UpdateGlobalDeckResponse
	(*GetGlobalDeckInfoByIDRequest)(nil),   // 7: global_deck.GetGlobalDeckInfoByIDRequest
	(*GetGlobalDeckInfoByIDResponse)(nil),  // 8: global_deck.GetGlobalDeckInfoByIDResponse
	(*DeleteGlobalDeckRequest)(nil),        // 9: global_deck.DeleteGlobalDeckRequest
	(*DeleteGlobalDeckResponse)(nil),       // 10: global_deck.DeleteGlobalDeckResponse
	(*SearchGlobalDecksRequest)(nil),       // 11: global_deck.SearchGlobalDecksRequest
	(*SearchGlobalDecksResponse)(nil),      // 12: global_deck.SearchGlobalDecksResponse
	(*SearchResultDeck)(nil),               // 13: global_deck.SearchResultDeck
	(*AddDeckToLearningDecksRequest)(nil),  // 14: global_deck.AddDeckToLearningDecksRequest
	(*AddDeckToLearningDecksResponse)(nil), // 15: global_deck.AddDeckToLearningDecksResponse
	(*AddEditorToGlobalDeckRequest)(nil),   // 16: global_deck.AddEditorToGlobalDeckRequest
	(*AddEditorToGlobalDeckResponse)(nil),  // 17: global_deck.AddEditorToGlobalDeckResponse
	(*DemoteEditorToLearnerRequest)(nil),   // 18: global_deck.DemoteEditorToLearnerRequest
	(*DemoteEditorToLearnerResponse)(nil),  // 19: global_deck.DemoteEditorToLearnerResponse
	(*timestamppb.Timestamp)(nil),          // 20: google.protobuf.Timestamp
}
var file_proto_global_deck_proto_depIdxs = []int32{
	20, // 0: global_deck.GlobalDeck.created_at:type_name -> google.protobuf.Timestamp
	20, // 1: global_deck.GlobalDeck.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: global_deck.GetEditableDecksResponse.listOfGlobalDecks:type_name -> global_deck.GlobalDeck
	0,  // 3: global_deck.UpdateGlobalDeckRequest.globalDeck:type_name -> global_deck.GlobalDeck
	0,  // 4: global_deck.UpdateGlobalDeckResponse.conflictDeck:type_name -> global_deck.GlobalDeck
	0,  // 5: global_deck.GetGlobalDeckInfoByIDResponse.globalDeck:type_name -> global_deck.GlobalDeck
	13, // 6: global_deck.SearchGlobalDecksResponse.results:type_name -> global_deck.SearchResultDeck
	0,  // 7: global_deck.SearchResultDeck.deck:type_name -> global_deck.GlobalDeck
	1,  // 8: global_deck.GlobalDeckService.CreateGlobalDeck:input_type -> global_deck.CreateGlobalDeckRequest
	3,  // 9: global_deck.GlobalDeckService.GetEditableGlobalDecks:input_type -> global_deck.GetEditableDecksRequest
	5,  // 10: global_deck.GlobalDeckService.UpdateGlobalDeck:input_type -> global_deck.UpdateGlobalDeckRequest
	7,  // 11: global_deck.GlobalDeckService.GetGlobalDeckInfoByID:input_type -> global_deck.GetGlobalDeckInfoByIDRequest
	9,  // 12: global_deck.GlobalDeckService.DeleteGlobalDeck:input_type -> global_deck.DeleteGlobalDeckRequest
	11, // 13: global_deck.GlobalDeckService.SearchGlobalDecks:input_type -> global_deck.SearchGlobalDecksRequest
	14, // 14: global_deck.GlobalDeckService.AddDeckToLearningDecks:input_type -> global_deck.AddDeckToLearningDecksRequest
	16, // 15: global_deck.GlobalDeckService.AddEditorToGlobalDeck:input_type -> global_deck.AddEditorToGlobalDeckRequest
	18, // 16: global_deck.GlobalDeckService.DemoteEditorToLearner:input_type -> global_deck.DemoteEditorToLearnerRequest
	2,  // 17: global_deck.GlobalDeckService.CreateGlobalDeck:output_type -> global_deck.CreateGlobalDeckResponse
	4,  // 18: global_deck.GlobalDeckService.GetEditableGlobalDecks:output_type -> global_deck.GetEditableDecksResponse
	6,  // 19: global_deck.GlobalDeckService.UpdateGlobalDeck:output_type -> global_deck.UpdateGlobalDeckResponse
	8,  // 20: global_deck.GlobalDeckService.GetGlobalDeckInfoByID:output_type -> global_deck.GetGlobalDeckInfoByIDResponse
	10, // 21: global_deck.GlobalDeckService.DeleteGlobalDeck:output_type -> global_deck.DeleteGlobalDeckResponse
	12, // 22: global_deck.GlobalDeckService.SearchGlobalDecks:output_type -> global_deck.SearchGlobalDecksResponse
	15, // 23: global_deck.GlobalDeckService.AddDeckToLearningDecks:output_type -> global_deck.AddDeckToLearningDecksResponse
	17, // 24: global_deck.GlobalDeckService.AddEditorToGlobalDeck:output_type -> global_deck.AddEditorToGlobalDeckResponse
	19, // 25: global_deck.GlobalDeckService.DemoteEditorToLearner:output_type -> global_deck.DemoteEditorToLearnerResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_global_deck_proto_init() }
func file_proto_global_deck_proto_init() {
	if File_proto_global_deck_proto != nil {
		return
	}
	file_proto_global_deck_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_global_deck_proto_rawDesc), len(file_proto_global_deck_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_global_deck_proto_goTypes,
		DependencyIndexes: file_proto_global_deck_proto_depIdxs,
		MessageInfos:      file_proto_global_deck_proto_msgTypes,
	}.Build()
	File_proto_global_deck_proto = out.File
	file_proto_global_deck_proto_goTypes = nil
	file_proto_global_deck_proto_depIdxs = nil
}
