// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/validation_service.proto

package validation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ValidationService_CheckUserNameAvailability_FullMethodName  = "/user.validation.ValidationService/CheckUserNameAvailability"
	ValidationService_CheckUserEmailAvailability_FullMethodName = "/user.validation.ValidationService/CheckUserEmailAvailability"
	ValidationService_CheckPasswordValidity_FullMethodName      = "/user.validation.ValidationService/CheckPasswordValidity"
)

// ValidationServiceClient is the client API for ValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidationServiceClient interface {
	CheckUserNameAvailability(ctx context.Context, in *CheckUserNameAvailabilityRequest, opts ...grpc.CallOption) (*CheckUserNameAvailabilityResponse, error)
	CheckUserEmailAvailability(ctx context.Context, in *CheckUserEmailAvailabilityRequest, opts ...grpc.CallOption) (*CheckUserEmailAvailabilityResponse, error)
	CheckPasswordValidity(ctx context.Context, in *CheckUserPasswordAvailabilityRequest, opts ...grpc.CallOption) (*CheckUserPasswordAvailabilityResponse, error)
}

type validationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidationServiceClient(cc grpc.ClientConnInterface) ValidationServiceClient {
	return &validationServiceClient{cc}
}

func (c *validationServiceClient) CheckUserNameAvailability(ctx context.Context, in *CheckUserNameAvailabilityRequest, opts ...grpc.CallOption) (*CheckUserNameAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUserNameAvailabilityResponse)
	err := c.cc.Invoke(ctx, ValidationService_CheckUserNameAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validationServiceClient) CheckUserEmailAvailability(ctx context.Context, in *CheckUserEmailAvailabilityRequest, opts ...grpc.CallOption) (*CheckUserEmailAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUserEmailAvailabilityResponse)
	err := c.cc.Invoke(ctx, ValidationService_CheckUserEmailAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validationServiceClient) CheckPasswordValidity(ctx context.Context, in *CheckUserPasswordAvailabilityRequest, opts ...grpc.CallOption) (*CheckUserPasswordAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUserPasswordAvailabilityResponse)
	err := c.cc.Invoke(ctx, ValidationService_CheckPasswordValidity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidationServiceServer is the server API for ValidationService service.
// All implementations must embed UnimplementedValidationServiceServer
// for forward compatibility.
type ValidationServiceServer interface {
	CheckUserNameAvailability(context.Context, *CheckUserNameAvailabilityRequest) (*CheckUserNameAvailabilityResponse, error)
	CheckUserEmailAvailability(context.Context, *CheckUserEmailAvailabilityRequest) (*CheckUserEmailAvailabilityResponse, error)
	CheckPasswordValidity(context.Context, *CheckUserPasswordAvailabilityRequest) (*CheckUserPasswordAvailabilityResponse, error)
	mustEmbedUnimplementedValidationServiceServer()
}

// UnimplementedValidationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidationServiceServer struct{}

func (UnimplementedValidationServiceServer) CheckUserNameAvailability(context.Context, *CheckUserNameAvailabilityRequest) (*CheckUserNameAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserNameAvailability not implemented")
}
func (UnimplementedValidationServiceServer) CheckUserEmailAvailability(context.Context, *CheckUserEmailAvailabilityRequest) (*CheckUserEmailAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserEmailAvailability not implemented")
}
func (UnimplementedValidationServiceServer) CheckPasswordValidity(context.Context, *CheckUserPasswordAvailabilityRequest) (*CheckUserPasswordAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPasswordValidity not implemented")
}
func (UnimplementedValidationServiceServer) mustEmbedUnimplementedValidationServiceServer() {}
func (UnimplementedValidationServiceServer) testEmbeddedByValue()                           {}

// UnsafeValidationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidationServiceServer will
// result in compilation errors.
type UnsafeValidationServiceServer interface {
	mustEmbedUnimplementedValidationServiceServer()
}

func RegisterValidationServiceServer(s grpc.ServiceRegistrar, srv ValidationServiceServer) {
	// If the following call pancis, it indicates UnimplementedValidationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValidationService_ServiceDesc, srv)
}

func _ValidationService_CheckUserNameAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserNameAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationServiceServer).CheckUserNameAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationService_CheckUserNameAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationServiceServer).CheckUserNameAvailability(ctx, req.(*CheckUserNameAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidationService_CheckUserEmailAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserEmailAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationServiceServer).CheckUserEmailAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationService_CheckUserEmailAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationServiceServer).CheckUserEmailAvailability(ctx, req.(*CheckUserEmailAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidationService_CheckPasswordValidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserPasswordAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationServiceServer).CheckPasswordValidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationService_CheckPasswordValidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationServiceServer).CheckPasswordValidity(ctx, req.(*CheckUserPasswordAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidationService_ServiceDesc is the grpc.ServiceDesc for ValidationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.validation.ValidationService",
	HandlerType: (*ValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUserNameAvailability",
			Handler:    _ValidationService_CheckUserNameAvailability_Handler,
		},
		{
			MethodName: "CheckUserEmailAvailability",
			Handler:    _ValidationService_CheckUserEmailAvailability_Handler,
		},
		{
			MethodName: "CheckPasswordValidity",
			Handler:    _ValidationService_CheckPasswordValidity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/validation_service.proto",
}
