// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/user_deck_progress.proto

package user_deck_progress

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDeckProgress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeckId         int32                  `protobuf:"varint,2,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	LastReviewedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_reviewed_at,json=lastReviewedAt,proto3,oneof" json:"last_reviewed_at,omitempty"`
	Score          int32                  `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserDeckProgress) Reset() {
	*x = UserDeckProgress{}
	mi := &file_proto_user_deck_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeckProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeckProgress) ProtoMessage() {}

func (x *UserDeckProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_deck_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeckProgress.ProtoReflect.Descriptor instead.
func (*UserDeckProgress) Descriptor() ([]byte, []int) {
	return file_proto_user_deck_progress_proto_rawDescGZIP(), []int{0}
}

func (x *UserDeckProgress) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserDeckProgress) GetDeckId() int32 {
	if x != nil {
		return x.DeckId
	}
	return 0
}

func (x *UserDeckProgress) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserDeckProgress) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserDeckProgress) GetLastReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReviewedAt
	}
	return nil
}

func (x *UserDeckProgress) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetUserLearningProgressDecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLearningProgressDecksRequest) Reset() {
	*x = GetUserLearningProgressDecksRequest{}
	mi := &file_proto_user_deck_progress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLearningProgressDecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLearningProgressDecksRequest) ProtoMessage() {}

func (x *GetUserLearningProgressDecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_deck_progress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLearningProgressDecksRequest.ProtoReflect.Descriptor instead.
func (*GetUserLearningProgressDecksRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_deck_progress_proto_rawDescGZIP(), []int{1}
}

type GetUserLearningProgressDecksResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserDeckProgressList []*UserDeckProgress    `protobuf:"bytes,1,rep,name=user_deck_progress_list,json=userDeckProgressList,proto3" json:"user_deck_progress_list,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetUserLearningProgressDecksResponse) Reset() {
	*x = GetUserLearningProgressDecksResponse{}
	mi := &file_proto_user_deck_progress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLearningProgressDecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLearningProgressDecksResponse) ProtoMessage() {}

func (x *GetUserLearningProgressDecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_deck_progress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLearningProgressDecksResponse.ProtoReflect.Descriptor instead.
func (*GetUserLearningProgressDecksResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_deck_progress_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserLearningProgressDecksResponse) GetUserDeckProgressList() []*UserDeckProgress {
	if x != nil {
		return x.UserDeckProgressList
	}
	return nil
}

type UserProgressDecks struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserProgressDecks []*UserDeckProgress    `protobuf:"bytes,1,rep,name=user_progress_decks,json=userProgressDecks,proto3" json:"user_progress_decks,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserProgressDecks) Reset() {
	*x = UserProgressDecks{}
	mi := &file_proto_user_deck_progress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgressDecks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgressDecks) ProtoMessage() {}

func (x *UserProgressDecks) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_deck_progress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgressDecks.ProtoReflect.Descriptor instead.
func (*UserProgressDecks) Descriptor() ([]byte, []int) {
	return file_proto_user_deck_progress_proto_rawDescGZIP(), []int{3}
}

func (x *UserProgressDecks) GetUserProgressDecks() []*UserDeckProgress {
	if x != nil {
		return x.UserProgressDecks
	}
	return nil
}

type DeleteDeckFromLearningDecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        int32                  `protobuf:"varint,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeckFromLearningDecksRequest) Reset() {
	*x = DeleteDeckFromLearningDecksRequest{}
	mi := &file_proto_user_deck_progress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeckFromLearningDecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeckFromLearningDecksRequest) ProtoMessage() {}

func (x *DeleteDeckFromLearningDecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_deck_progress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeckFromLearningDecksRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeckFromLearningDecksRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_deck_progress_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDeckFromLearningDecksRequest) GetDeckId() int32 {
	if x != nil {
		return x.DeckId
	}
	return 0
}

type DeleteDeckFromLearningDecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeckFromLearningDecksResponse) Reset() {
	*x = DeleteDeckFromLearningDecksResponse{}
	mi := &file_proto_user_deck_progress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeckFromLearningDecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeckFromLearningDecksResponse) ProtoMessage() {}

func (x *DeleteDeckFromLearningDecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_deck_progress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeckFromLearningDecksResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeckFromLearningDecksResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_deck_progress_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDeckFromLearningDecksResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

var File_proto_user_deck_progress_proto protoreflect.FileDescriptor

const file_proto_user_deck_progress_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/user_deck_progress.proto\x12\x12user_deck_progress\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n" +
	"\x10UserDeckProgress\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\adeck_id\x18\x02 \x01(\x05R\x06deckId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12I\n" +
	"\x10last_reviewed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0elastReviewedAt\x88\x01\x01\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x05R\x05scoreB\x13\n" +
	"\x11_last_reviewed_at\"%\n" +
	"#GetUserLearningProgressDecksRequest\"\x83\x01\n" +
	"$GetUserLearningProgressDecksResponse\x12[\n" +
	"\x17user_deck_progress_list\x18\x01 \x03(\v2$.user_deck_progress.UserDeckProgressR\x14userDeckProgressList\"i\n" +
	"\x11UserProgressDecks\x12T\n" +
	"\x13user_progress_decks\x18\x01 \x03(\v2$.user_deck_progress.UserDeckProgressR\x11userProgressDecks\"=\n" +
	"\"DeleteDeckFromLearningDecksRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\x05R\x06deckId\"C\n" +
	"#DeleteDeckFromLearningDecksResponse\x12\x1c\n" +
	"\tisSuccess\x18\x01 \x01(\bR\tisSuccess2\xa9\x03\n" +
	"\x17UserDeckProgressService\x12\x91\x01\n" +
	"\x1cGetUserLearningProgressDecks\x127.user_deck_progress.GetUserLearningProgressDecksRequest\x1a8.user_deck_progress.GetUserLearningProgressDecksResponse\x12i\n" +
	"\x19SelectDecksForTodayReview\x12%.user_deck_progress.UserProgressDecks\x1a%.user_deck_progress.UserProgressDecks\x12\x8e\x01\n" +
	"\x1bDeleteDeckFromLearningDecks\x126.user_deck_progress.DeleteDeckFromLearningDecksRequest\x1a7.user_deck_progress.DeleteDeckFromLearningDecksResponseB@Z>infrastructure/grpc_infr/user_deck_progress;user_deck_progressb\x06proto3"

var (
	file_proto_user_deck_progress_proto_rawDescOnce sync.Once
	file_proto_user_deck_progress_proto_rawDescData []byte
)

func file_proto_user_deck_progress_proto_rawDescGZIP() []byte {
	file_proto_user_deck_progress_proto_rawDescOnce.Do(func() {
		file_proto_user_deck_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_deck_progress_proto_rawDesc), len(file_proto_user_deck_progress_proto_rawDesc)))
	})
	return file_proto_user_deck_progress_proto_rawDescData
}

var file_proto_user_deck_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_user_deck_progress_proto_goTypes = []any{
	(*UserDeckProgress)(nil),                     // 0: user_deck_progress.UserDeckProgress
	(*GetUserLearningProgressDecksRequest)(nil),  // 1: user_deck_progress.GetUserLearningProgressDecksRequest
	(*GetUserLearningProgressDecksResponse)(nil), // 2: user_deck_progress.GetUserLearningProgressDecksResponse
	(*UserProgressDecks)(nil),                    // 3: user_deck_progress.UserProgressDecks
	(*DeleteDeckFromLearningDecksRequest)(nil),   // 4: user_deck_progress.DeleteDeckFromLearningDecksRequest
	(*DeleteDeckFromLearningDecksResponse)(nil),  // 5: user_deck_progress.DeleteDeckFromLearningDecksResponse
	(*timestamppb.Timestamp)(nil),                // 6: google.protobuf.Timestamp
}
var file_proto_user_deck_progress_proto_depIdxs = []int32{
	6, // 0: user_deck_progress.UserDeckProgress.last_reviewed_at:type_name -> google.protobuf.Timestamp
	0, // 1: user_deck_progress.GetUserLearningProgressDecksResponse.user_deck_progress_list:type_name -> user_deck_progress.UserDeckProgress
	0, // 2: user_deck_progress.UserProgressDecks.user_progress_decks:type_name -> user_deck_progress.UserDeckProgress
	1, // 3: user_deck_progress.UserDeckProgressService.GetUserLearningProgressDecks:input_type -> user_deck_progress.GetUserLearningProgressDecksRequest
	3, // 4: user_deck_progress.UserDeckProgressService.SelectDecksForTodayReview:input_type -> user_deck_progress.UserProgressDecks
	4, // 5: user_deck_progress.UserDeckProgressService.DeleteDeckFromLearningDecks:input_type -> user_deck_progress.DeleteDeckFromLearningDecksRequest
	2, // 6: user_deck_progress.UserDeckProgressService.GetUserLearningProgressDecks:output_type -> user_deck_progress.GetUserLearningProgressDecksResponse
	3, // 7: user_deck_progress.UserDeckProgressService.SelectDecksForTodayReview:output_type -> user_deck_progress.UserProgressDecks
	5, // 8: user_deck_progress.UserDeckProgressService.DeleteDeckFromLearningDecks:output_type -> user_deck_progress.DeleteDeckFromLearningDecksResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_user_deck_progress_proto_init() }
func file_proto_user_deck_progress_proto_init() {
	if File_proto_user_deck_progress_proto != nil {
		return
	}
	file_proto_user_deck_progress_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_deck_progress_proto_rawDesc), len(file_proto_user_deck_progress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_deck_progress_proto_goTypes,
		DependencyIndexes: file_proto_user_deck_progress_proto_depIdxs,
		MessageInfos:      file_proto_user_deck_progress_proto_msgTypes,
	}.Build()
	File_proto_user_deck_progress_proto = out.File
	file_proto_user_deck_progress_proto_goTypes = nil
	file_proto_user_deck_progress_proto_depIdxs = nil
}
