enum FailureCode {
  networkError,
  unauthorized,
  userNotFound,
  serverError,
  unknownError,
  deckCreatedButFailedToLoad,
  titleIsEmpty,
  cardsLoadFailedDueToNetwork,
  cardsLoadFailedDueToUnknownFailure,
  decksLoadFailedDueToNetwork,
  decksLoadFailedDueToUnknownFailure,
  cardCreatedButFailedToLoadCards,
  invalidCardArgument,
  deckPermissionDenied,
  cardDeletedButFailedToLoadCards,
  deckDeletedButFailedToLoadDecks,
  suchPermissionAlreadyExists,
  conflictCardError,
  deckUpdatedButFailedGetInfo,
  conflictDeckError,
  cardWasDeletedRefreshData,
  noCards,
  noNewCards,
  noFamiliarCards,
  noDecksForDailyTasks,
  noCardsForReview,
  deletedButFailedLoadDecks,
  authorCantDelete,
  needAuthorization,
  incorrectOrExpiredCode,
  incorrectPassword,
  newPasswordSuccessfullySent,
}


