// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/validation_service.proto

package validation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckUserNameAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserNameAvailabilityRequest) Reset() {
	*x = CheckUserNameAvailabilityRequest{}
	mi := &file_proto_validation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserNameAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserNameAvailabilityRequest) ProtoMessage() {}

func (x *CheckUserNameAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserNameAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckUserNameAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_validation_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckUserNameAvailabilityRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type CheckUserNameAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserNameAvailabilityResponse) Reset() {
	*x = CheckUserNameAvailabilityResponse{}
	mi := &file_proto_validation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserNameAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserNameAvailabilityResponse) ProtoMessage() {}

func (x *CheckUserNameAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserNameAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckUserNameAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_validation_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckUserNameAvailabilityResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type CheckUserEmailAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserEmailAvailabilityRequest) Reset() {
	*x = CheckUserEmailAvailabilityRequest{}
	mi := &file_proto_validation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserEmailAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserEmailAvailabilityRequest) ProtoMessage() {}

func (x *CheckUserEmailAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserEmailAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckUserEmailAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_validation_service_proto_rawDescGZIP(), []int{2}
}

func (x *CheckUserEmailAvailabilityRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type CheckUserEmailAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserEmailAvailabilityResponse) Reset() {
	*x = CheckUserEmailAvailabilityResponse{}
	mi := &file_proto_validation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserEmailAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserEmailAvailabilityResponse) ProtoMessage() {}

func (x *CheckUserEmailAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserEmailAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckUserEmailAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_validation_service_proto_rawDescGZIP(), []int{3}
}

func (x *CheckUserEmailAvailabilityResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type CheckUserPasswordAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserPasswordAvailabilityRequest) Reset() {
	*x = CheckUserPasswordAvailabilityRequest{}
	mi := &file_proto_validation_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserPasswordAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPasswordAvailabilityRequest) ProtoMessage() {}

func (x *CheckUserPasswordAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validation_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPasswordAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckUserPasswordAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_validation_service_proto_rawDescGZIP(), []int{4}
}

func (x *CheckUserPasswordAvailabilityRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CheckUserPasswordAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserPasswordAvailabilityResponse) Reset() {
	*x = CheckUserPasswordAvailabilityResponse{}
	mi := &file_proto_validation_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserPasswordAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPasswordAvailabilityResponse) ProtoMessage() {}

func (x *CheckUserPasswordAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validation_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPasswordAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckUserPasswordAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_validation_service_proto_rawDescGZIP(), []int{5}
}

func (x *CheckUserPasswordAvailabilityResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_proto_validation_service_proto protoreflect.FileDescriptor

const file_proto_validation_service_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/validation_service.proto\x12\x0fuser.validation\">\n" +
	" CheckUserNameAvailabilityRequest\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\"F\n" +
	"!CheckUserNameAvailabilityResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable\"A\n" +
	"!CheckUserEmailAvailabilityRequest\x12\x1c\n" +
	"\tuserEmail\x18\x01 \x01(\tR\tuserEmail\"G\n" +
	"\"CheckUserEmailAvailabilityResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable\"B\n" +
	"$CheckUserPasswordAvailabilityRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"B\n" +
	"%CheckUserPasswordAvailabilityResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid2\xa9\x03\n" +
	"\x11ValidationService\x12\x82\x01\n" +
	"\x19CheckUserNameAvailability\x121.user.validation.CheckUserNameAvailabilityRequest\x1a2.user.validation.CheckUserNameAvailabilityResponse\x12\x85\x01\n" +
	"\x1aCheckUserEmailAvailability\x122.user.validation.CheckUserEmailAvailabilityRequest\x1a3.user.validation.CheckUserEmailAvailabilityResponse\x12\x86\x01\n" +
	"\x15CheckPasswordValidity\x125.user.validation.CheckUserPasswordAvailabilityRequest\x1a6.user.validation.CheckUserPasswordAvailabilityResponseB5Z3infrastructure/grpc_infr/user/validation;validationb\x06proto3"

var (
	file_proto_validation_service_proto_rawDescOnce sync.Once
	file_proto_validation_service_proto_rawDescData []byte
)

func file_proto_validation_service_proto_rawDescGZIP() []byte {
	file_proto_validation_service_proto_rawDescOnce.Do(func() {
		file_proto_validation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_validation_service_proto_rawDesc), len(file_proto_validation_service_proto_rawDesc)))
	})
	return file_proto_validation_service_proto_rawDescData
}

var file_proto_validation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_validation_service_proto_goTypes = []any{
	(*CheckUserNameAvailabilityRequest)(nil),      // 0: user.validation.CheckUserNameAvailabilityRequest
	(*CheckUserNameAvailabilityResponse)(nil),     // 1: user.validation.CheckUserNameAvailabilityResponse
	(*CheckUserEmailAvailabilityRequest)(nil),     // 2: user.validation.CheckUserEmailAvailabilityRequest
	(*CheckUserEmailAvailabilityResponse)(nil),    // 3: user.validation.CheckUserEmailAvailabilityResponse
	(*CheckUserPasswordAvailabilityRequest)(nil),  // 4: user.validation.CheckUserPasswordAvailabilityRequest
	(*CheckUserPasswordAvailabilityResponse)(nil), // 5: user.validation.CheckUserPasswordAvailabilityResponse
}
var file_proto_validation_service_proto_depIdxs = []int32{
	0, // 0: user.validation.ValidationService.CheckUserNameAvailability:input_type -> user.validation.CheckUserNameAvailabilityRequest
	2, // 1: user.validation.ValidationService.CheckUserEmailAvailability:input_type -> user.validation.CheckUserEmailAvailabilityRequest
	4, // 2: user.validation.ValidationService.CheckPasswordValidity:input_type -> user.validation.CheckUserPasswordAvailabilityRequest
	1, // 3: user.validation.ValidationService.CheckUserNameAvailability:output_type -> user.validation.CheckUserNameAvailabilityResponse
	3, // 4: user.validation.ValidationService.CheckUserEmailAvailability:output_type -> user.validation.CheckUserEmailAvailabilityResponse
	5, // 5: user.validation.ValidationService.CheckPasswordValidity:output_type -> user.validation.CheckUserPasswordAvailabilityResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_validation_service_proto_init() }
func file_proto_validation_service_proto_init() {
	if File_proto_validation_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_validation_service_proto_rawDesc), len(file_proto_validation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_validation_service_proto_goTypes,
		DependencyIndexes: file_proto_validation_service_proto_depIdxs,
		MessageInfos:      file_proto_validation_service_proto_msgTypes,
	}.Build()
	File_proto_validation_service_proto = out.File
	file_proto_validation_service_proto_goTypes = nil
	file_proto_validation_service_proto_depIdxs = nil
}
